### ISSUE TITLE
[ENHANCEMENT] CAN YOU MAKE IT AS A PACKAGE 

### ISSUE THREAD

**Issue by iamrishan** [jr1221/ntfy_dart#1]
can you make a package based on nfty api and publish to [Pub.dev](https://pub.dev/) where we can include the package on our project to send, recieve messages via ntfy topics

basically, I'm implementing ntfy API on my app to receive all the notifications on my topics. using nfty API in dart is kinda tricky because i didn't understand the stream concept of flutter. 

it is nice to have a package to it so we can receive/send our messages via our own app using nftyapi

**Comment by jr1221** [comment]
I'll look into pub packaging guidelines.  For the meantime, you can use this as a git dependency.  
See https://dart.dev/tools/pub/dependencies#git-packages
If you find any bugs, missing features you need, etc, feel free to open an issue!
